# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vintage Keyboard Repair
phone-number: 510-527-2067
description: > # this means to ignore newlines until "baseurl:"
  Vintage Keyboard Repair
baseurl: "/mattCunitzGithubPages" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "https://fogg4444.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

collections:
  - forsale

permalink: pretty

# markdown: rdiscount

prose:
  rooturl: '_posts'
  siteurl: 'https://fogg4444.github.io/mattCunitzGithubPages/'
  relativeLinks: 'https://fogg4444.github.io/mattCunitzGithubPages/links.jsonp'
  media: 'assets/images'
  
  metadata:
    _posts/forsale:
      - name: "layout"
        field:
          element: "hidden"
          value: "forsale"
      - name: "categories"
        field:
          element: "hidden"
          value: "forsale"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
