# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vintage Keyboard Repair
phone-number: 510-527-2067
description: > # this means to ignore newlines until "baseurl:"
  Vintage Keyboard Repair
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://www.vintagekeyboardrepair.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

collections:
  - forsale

permalink: pretty

# markdown: rdiscount

prose:
  rooturl: ''
  ignore: ['_includes', '_layouts', '_sass', '_site', 'about.md', 'blog.rss', 'CNAME', 'css', 'favicon.ico', 'feed.xml', 'Gemfile', 'Gemfile.lock', 'index.html', 'LICENCE.md', 'links.jsonp', 'README.md', 'scratch.html', 'site.css', 'site.js', '.gitignore', '.ruby-version', '_config.yml', 'forsale']
  siteurl: 'http://www.vintagekeyboardrepair.com'
  relativeLinks: 'http://www.vintagekeyboardrepair.com/links.jsonp'
  media: 'assets/images'
  
  metadata:
    _posts/forsale:
      - name: "layout"
        field:
          element: "hidden"
          value: "forsale"
      - name: "categories"
        field:
          element: "hidden"
          value: "forsale"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        value: true
